[lms_local]
host=localhost
user=pranavrnayakn
dbname=lms_local
port=5432

[lms_dev]
host=localhost
user=pranavrnayakn
dbname=lms_dev
port=5432

[lms_uat]
host=localhost
user=pranavrnayakn
dbname=lms_uat
port=5432

[lms_prod]
host=localhost
user=pranavrnayakn
dbname=lms_prod
port=5432
